config/routes.rb
Rails.application.routes.draw do
  resources :discoveries
  resources :trophies
  resources :expeditions
  resources :places
  resources :explorers
  resources :users
  resources :hiscores
  root to: 'pages#home'
  get '/login', to: 'sessions#new', as: "login"
  get '/info', to: 'sessions#info', as: "info"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: "logout"
  get '/explorers/:id/trophy', to: 'explorers#trophyhall', as: 'trophyhall'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :explorers
    has_secure_password 
    validates :name, presence: true, uniqueness: true

    def averageExplorerWealth
        numExplorers = self.explorers.count
        count = 0
        self.explorers.each { |explorer| count+= explorer.money }

        count / numExplorers
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :findUser, only: [:show, :edit, :update]



    def new
        if @logged_in 
            redirect_to @logged_in
        else
            @user = User.new
        end
        
    end

    def create
    
        @user = User.new(userParams)

        if @user.save 
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash[:error] = @user.errors.full_messages
            redirect_to new_user_path
        end

    end

    def show
    # byebug
        @id = @user.id
        if @user == @logged_in 
            render :show
        else 
            flash[:error] = "LMAO"
            redirect_to login_path
        end
    end

    def edit 
    end

    def update
        @user.assign_attributes(userParams)
        if @user.save 
            redirect_to @user
        else
            flash[:error] = @user.errors.full_messages
            redirect_to edit_user_path(@user)
        end
    end


    private 

    def userParams
        params.require(:user).permit(:name, :password, :password_confirmation)
    end

    def findUser
        @user = User.find(params[:id])
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="mapBack">
<div class="exped"><div class="expedInner"><br>
<h1>New User</h1>

<%= form_for @user do |f|%>
 <%= f.label "Name"%><br>
 <%= f.text_field :name%>
<br><br>
 <%= f.label "Password"%><br>
 <%= f.password_field :password %>
<br><br>
 <%= f.label "Password Confirmation"%><br>
 <%= f.password_field :password_confirmation %>
<br><br>
 <%= f.submit class:"btn btn-outline-dark btn-lg btn-block" %>
<br>
 <% end %>

 </div>
 </div>
 </div>

app/views/users/show.html.erb
<div class="mapBack">
<div class="exped"><div class="expedInner"><br>
<h1><%="#{@user.name}'s page"%></h1>

<%# <%= link_to "Log Out", logout_path, method: :delete %> 
<form action="<%=new_explorer_path%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Recruit a New Explorer</button></form>
   
<%# button_to "Recruit new Explorer", new_explorer_path(TESTID: @id), method: :get%>
<br><h2>My Explorers : </h2>

<%if @user.explorers[0] %>
    <% @user.explorers.each do |explorer| %>
    <form action="<%=explorer_path(explorer)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'><%=explorer.name%></button></form>
   <% end %>
    <%else %>
    <p> You don't have any explorers yet </p>
<% end %><br>
</div></div></div>

 <!--
 <div class="mapBack">
<div class="exped"><div class="expedInner">
<br><h1> Login </h1>
<% if flash[:error] %>
<%= flash[:error] %>
<% end %>

<%= form_for :login do |f|%>
 <%= f.label "Name"%><br>
 <%= f.text_field :name, autofocus: true %>
<br><br>
 <%= f.label "Password"%><br>
 <%= f.password_field :password %>
<br><br>
 <%= f.submit "Log In" %>
<br><br>
 <% end %></div></div></div>-->