config/routes.rb
Rails.application.routes.draw do
  resources :discoveries
  resources :trophies
  resources :expeditions
  resources :places
  resources :explorers
  resources :users
  resources :hiscores
  root to: 'pages#home'
  get '/login', to: 'sessions#new', as: "login"
  get '/info', to: 'sessions#info', as: "info"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: "logout"
  get '/explorers/:id/trophy', to: 'explorers#trophyhall', as: 'trophyhall'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/explorer.rb
class Explorer < ApplicationRecord
    belongs_to :user
    has_many :trophies
    has_many :expeditions
    has_many :places, through: :expeditions

    validates :name, presence: true
    validates :name, format: {:with => /\A[a-zA-Z0-9]*\z|\s/, message: "must not contain special characters"}
    validates :name, uniqueness: true


    def self.wealthiest
        sortByMoney(all)
    end


    def self.search(search)
        if search 
            sortByMoney( all.select { |explorer|  explorer.user.name == search } )
        else
            sortByMoney(all)
        end
    end


    private
    def self.sortByMoney(array)
        array.sort_by { |explorer| -(explorer.money)}
    end


end

app/controllers/explorers_controller.rb
class ExplorersController < ApplicationController
    before_action :findExplorer, only: [:show, :edit, :update, :trophyhall]

    def index
        @explorers = Explorer.all
    end
    
    def new
        # byebug
            @explorer = Explorer.new
            @user_id = session[:user_id]
        
      
    end

    def create
    #    byebug
    @explorer = Explorer.new(explorerParams)
    @explorer.assign_attributes(user_id:params[:user_id])
  
        if @explorer.save
            @explorer.update(user_id:params[:user_id])
            redirect_to explorer_path(@explorer)
        else 
            flash[:error] = @explorer.errors.full_messages
            redirect_to new_explorer_path
        end

    end

    def show
        @user = User.find(@explorer.user_id)
        @id = @user.id
        if @user == @logged_in 
            render :show
        else 
            flash[:error] = "LMAO from Explorers"
            redirect_to login_path
        end
    end

    def edit 
    end

    def update
        @explorer = Explorer.update(explorerParams)
        redirect_to explorer_path(@explorer)
    end

    def trophyhall
        @trophies = @explorer.trophies
        render "trophy"
    end


    private 

    def explorerParams
        params.require(:explorer).permit(:name, :user_id)
    end

    def findExplorer
        @explorer = Explorer.find(params[:id])
    end


end

app/helpers/explorers_helper.rb
module ExplorersHelper
end

app/views/explorers/_form.html.erb
<div class="mapBack">
<div class="exped"><div class="expedInner"><br>
<%if flash[:error]%>
    <%=flash[:error][1]%><br>
<%end%>
<br>
<%= form_for @explorer do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %>

<%= hidden_field_tag :user_id, @user_id%>
<br><br>
<%= f.submit class:"btn btn-outline-dark btn-lg btn-block"%>
<% end %><br>
</div>
</div>
</div>

app/views/explorers/edit.html.erb
<%= render 'form' %>

app/views/explorers/index.html.erb
<h1> Explorers </h1>

app/views/explorers/new.html.erb
<%= render 'form' %>

app/views/explorers/show.html.erb
<div class="mapBack">
<div class="exped"><div class="expedInner"><br>
<h1><%= @explorer.name %></h1>
Money : <%= @explorer.money < 1 ? 0 : @explorer.money %>
<%# link_to 'View My Trophies', trophyhall_path(@explorer)%>
<form action="<%=trophyhall_path(@explorer)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>View My Trophies</button></form>
<form action="<%=new_expedition_path%>"><br>
<input id="explorerID" name="explorerID" type="hidden" value="<%=@explorer.id%>">
<button type='submit' class='btn btn-outline-dark btn-lg btn-block'>New Expedition</button></form>

<%# link_to 'New Expediton', new_expedition_path(explorerID: @explorer.id)%>
<br>


<br>

<%# button_to "Back", user_path(@user), method: :get%>
<form action="<%=user_path(@user)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Back</button></form>
<br>
</div></div>

app/views/explorers/trophy.html.erb
<div class="mapBack">
<div class="expedTroph"><div class="expedInner">
<br>
<h1> <%= @explorer.name %>'s Trophies </h1>
<br>
<table style="width:100%">
<tr>
    <th>Trophy Name</th>
    <th>Trophy Value</th>
</tr>
<% @trophies.each do |trophy| %> 
<tr><td><%="#{trophy.name}"%></td> 
    <td><%="#{trophy.value}"%></td></tr>
<%end %>
</table>
<br><br>
<%#button_to "Back", explorer_path(@explorer), method: :get %>
<form action="<%=explorer_path(@explorer)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Back</button></form>
<br>  
</div></div></div>