config/routes.rb
Rails.application.routes.draw do
  resources :discoveries
  resources :trophies
  resources :expeditions
  resources :places
  resources :explorers
  resources :users
  resources :hiscores
  root to: 'pages#home'
  get '/login', to: 'sessions#new', as: "login"
  get '/info', to: 'sessions#info', as: "info"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: "logout"
  get '/explorers/:id/trophy', to: 'explorers#trophyhall', as: 'trophyhall'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/expedition.rb
class Expedition < ApplicationRecord
    belongs_to :place
    belongs_to :explorer
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
    before_action :findExpedition, only: [:show, :edit, :update]

    def new
        @expedition = Expedition.new
        @places = Place.all
        @explorer_id = params[:explorerID]
        @explorer = Explorer.find(@explorer_id)
    end

    def create
        
        @expedition = Expedition.new(expeditionParams)
        @expedition.assign_attributes(explorer_id: params[:explorerID])

        if @expedition.save
        @explorer = Explorer.find(params[:explorerID])
            @explorer.rations = 100

            if @expedition.hasGuide 
                @explorer.money -= 10
            end

            if @expedition.hasWeapon
                @explorer.money -= 5000
            end
            @explorer.save

            redirect_to @expedition
        else
            flash[:error] = @expedition.errors.full_messages
            redirect_to new_expedition_path
        end

    end

    def index
    end

    def show
        @user = @expedition.explorer.user
        @id = @user.id
        if @user == @logged_in 
            @place = @expedition.place
            placename = @place.name
            @explorer = @expedition.explorer 


            if @expedition.progress == 7 || @expedition.progress == 26 || @explorer.rations < 1
                @img = "#{placename}/img7.jpg"
                @over = true
                render :show
                return
            end

            # check progress and display appropriate image
            @img = "#{placename}/img#{@expedition.progress}.jpg"
          
            if params[:explore] 
                if @explorer.rations < 1
                    render :show
                    return
                end
                @explored = true
                @explorer.rations -= 10
                @explorer.save
                # byebug
            discovery = @expedition.place.discoveryChance(@expedition.progress) #returns discovery instance
                if discovery 
                    # byebug
                    @dname = discovery.name
                    @demoji = discovery.emoji(@dname)
                    @guide = []
                    @trophy = []
                    ration_change = discovery.resolve(@expedition, @trophy, @guide)
                    # byebug

                    @explorer.rations += ration_change
                    @explorer.save
                else
                    @guide = ["This place is empty; You found nothing and consumed 10 🍗🍗🍗"]
                end

                if @place.roll < 51 && @expedition.progress == 5
                    value = @place.roll * 4000
                    @guide = ["You found a secret room!", "In this room you find Precious Treasure worth #{value}!"] 
                    @explorer.money += value
                    @explorer.save 
                    Trophy.create(explorer_id: @explorer.id, name: "Precious Treasure", value: value )  
                    @expedition.progress = 25
                    @img = "#{placename}/img#{@expedition.progress}.jpg"
                    @expedition.save 
                end
        
            #check if early or later area (how do we check for this
                            # new column called progress in Place? increment each time explorer :move_on ) 
                #assign modifier based on ^
                #roll for chance of a discovery (w modifier)
                #if discovery, then roll for what kind of outcome (w modifier)
                #decrement explorer rations
            elsif params[:move_on]
                #increment progress 
                #check if guide
                #decrement (^more if) rations 
                @explorer.rations -= 15
                @explorer.save
                @expedition.progress += 1
                @expedition.save
                @img = "#{placename}/img#{@expedition.progress}.jpg"
                if @expedition.progress == 7 || @expedition.progress == 26
                    @img = "#{placename}/img7.jpg"
                    @over = true
                end
                params[:move_on] = false
                render :show
                return
            end
        
        else 
            flash[:error] = "LMAO from Expedition"
            redirect_to login_path
        end

        
    end


    def edit 
    end

    def update
    end


    private 

    def expeditionParams
        params.require(:expedition).permit(:place_id, :hasWeapon, :hasGuide)
    end

    def findExpedition
        @expedition = Expedition.find(params[:id])
    end


end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/views/expeditions/new.html.erb
<%if flash[:error]%>
    <% flash[:error].each do |error|%>
        <%=error%>
    <% end %>
<% end %>
<div class="mapBack">
<div class="exped">
<div class="expedInner">
<br>
<%=form_for @expedition do |f|%>

<%= f.label "Location"%>
<%= f.collection_select :place_id, @places, :id, :name%>
<br>
<% if @explorer.money > 5000 %>
<%= f.label "Rent Weapon?", "Rent Weapon?"%>
<%= f.check_box :hasWeapon %>
<% else %>
<%= "You are too poor to afford a weapon!!"%>
<% end %>
<br>
<% if @explorer.money > -1 %>
<%= f.label "hire yoan as guide?", "Hire Yoan as Guide?"%>
<%= f.check_box :hasGuide%>
<% else %>
<%= "Wow you are so poor that you can't even afford Yoan!!"%>
<% end %>

<%= hidden_field_tag :explorerID, @explorer_id %>
<br> 

<%= f.submit class:"btn btn-outline-dark btn-lg btn-block"%>

<% end %>
<form action="<%=explorer_path(@explorer)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Back to Explorer Profile</button></form>
 
<%# button_to "Back to Explorer Profile", explorer_path(@explorer), method: :get%>
<br>
</div></div></div>

app/views/expeditions/show.html.erb
<div class="mapBackExped">
<div class="expedExped">
<div class="expedInner">
<%unless @over %><br>
    <%= image_tag @img, class:"img" %><br>
    Expedition at <%= @place.name %>, 🍗🍗🍗 : <%= @explorer.rations > 0 ? @explorer.rations : 0 %>
    <% if @expedition.hasWeapon%>
    <%= ", ⚔️You are carrying a weapon⚔️"%>,
    <% end %>
    <% if @expedition.hasGuide%>
    <%= "🕺🏻Yoan is guiding you🕺🏻"%>
    <% end %>
<br>

    <% if @dname  %>
    <%= "You found a #{@dname}#{@demoji}"%>
    <% end %>
   
    <% if @trophy%>
        <%@trophy.each { |g| %> 
        <p> <%=g%> </p>
        <%}%>
    <% end %>
    <br>
    
    <% if @guide %>
        <%@guide.each { |g| %>
        <p> <%=g%></p>
        <%}%>

    <% end %>
    
<br>

    <!--Logic for sending back to current page with new params-->
    <% unless @explored%>
    <%# button_to "Explore", expedition_path(@expedition), method: :get, params: {explore: true}%>
    <form action="<%=expedition_path(@expedition)%>">
    <input id="explore" name="explore" type="hidden" value="<%=true%>">
    <button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Explore</button></form>

    <% end %>
    <%# button_to "Press Forward", expedition_path(@expedition), method: :get, params: {move_on: true}%>
     <form action="<%=expedition_path(@expedition)%>">
    <input id="move_on" name="move_on" type="hidden" value="<%=true%>">
    <button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Press Forward</button></form>
    <br>
    
    

<%else %> <br>
    <%= image_tag @img, class:"img"%><br>
    <%if @explorer.rations < 1%>
    You're out of food!
    <%else%>
    Good Job!
    <%# button_to "Go Home", explorer_path(@explorer), method: :get%>
    <%end%>
    <form action="<%=explorer_path(@explorer)%>"><button type='submit' class='btn btn-outline-dark btn-lg btn-block'>Go Home</button></form>
    
    <br>
<%end%>
</div></div></div>